Add Dawn and Horizon cards
CollinHeist/TitleCardMaker-CardTypes pull request #36
Opened 2024-07-24 06:23 UTC by Supremicus

Add Dawn and Horizon cards

2024-07-24 16:46 UTC, CollinHeist commented
@Supremicus Awesome work! These both look exceptional. I'll start taking a look when I have the time 👍🏻

2024-07-24 21:56 UTC, CollinHeist requested changes
Looks really good! If you are able to make these changes (at least for the ones which are non-formatting related) then it should be good.

2024-07-24 21:56 UTC, CollinHeist commented on Supremicus/DawnTitleCard.py
> +        'episode_prefix', 'episode_text', 'hide_season_text', 'hide_episode_text',
```suggestion
        'episode_text', 'hide_season_text', 'hide_episode_text',
```

2024-07-24 21:56 UTC, CollinHeist commented on Supremicus/DawnTitleCard.py
> +    ARCHIVE_NAME = 'dawn'
```suggestion
    ARCHIVE_NAME = 'Dawn'
```
This is just to better align with the archive naming convention of all other card types

2024-07-24 21:56 UTC, CollinHeist commented on Supremicus/DawnTitleCard.py
> +    __GRADIENT_IMAGE = str(RemoteFile('Supremicus', 'ref/overlays/gradient.png'))
```suggestion
    EPISODE_TEXT_FONT = RemoteFile('Supremicus', 'ref/fonts/ExoSoft-Medium.ttf')

    """Source path for CRT overlays to be overlayed if enabled"""
    __OVERLAY_PLAIN = RemoteFile('Supremicus', 'ref/overlays/overlay_plain.png')
    __OVERLAY_PLAIN_BEZEL = RemoteFile('Supremicus', 'ref/overlays/overlay_plain_bezel.png')
    __OVERLAY_PLAY = RemoteFile('Supremicus', 'ref/overlays/overlay_play.png')
    __OVERLAY_PLAY_BEZEL = RemoteFile('Supremicus', 'ref/overlays/overlay_play_bezel.png')
    __OVERLAY_REWIND = RemoteFile('Supremicus', 'ref/overlays/overlay_rewind.png')
    __OVERLAY_REWIND_BEZEL = RemoteFile('Supremicus', 'ref/overlays/overlay_rewind_bezel.png')

    """Source path for the gradient image"""
    __GRADIENT_IMAGE = RemoteFile('Supremicus', 'ref/overlays/gradient.png')
```
This is so you can treat these as `Path` objects and call `resolve()` on them

2024-07-24 21:56 UTC, CollinHeist commented on Supremicus/DawnTitleCard.py
> +                description='Vertical Shift for Episode Text.',
```suggestion
                description='Vertical Shift for Episode Text',
```

2024-07-24 21:56 UTC, CollinHeist commented on Supremicus/DawnTitleCard.py
> +                description='Horizontal shift for Title Text.',
```suggestion
                description='Horizontal shift for the title text',
```

2024-07-24 21:56 UTC, CollinHeist commented on Supremicus/DawnTitleCard.py
> +                description='Color to use for the episode & title text stroke.',
```suggestion
                description='Color to use for the episode & title text stroke',
```

2024-07-24 21:56 UTC, CollinHeist commented on Supremicus/DawnTitleCard.py
> +                description='Character to separate season and episode text.',
```suggestion
                description='Character to separate season and episode text',
```

2024-07-24 21:56 UTC, CollinHeist commented on Supremicus/DawnTitleCard.py
> +                description='Horizontal alignment of text.',
```suggestion
                description='Horizontal alignment of text',
```

2024-07-24 21:56 UTC, CollinHeist commented on Supremicus/DawnTitleCard.py
> +                    'Default is <v>None</v>.'
```suggestion
                description='CRT TV Overlay Toggle',
                tooltip=(
                    'Either <v>nobezel</v> or <v>bezel</v>. Default is <v>None</v>.'
```

2024-07-24 21:56 UTC, CollinHeist commented on Supremicus/DawnTitleCard.py
> +                    'Will only work if CRT TV Overlay is enabled.'
```suggestion
                description='CRT TV Overlay Watched-Status Toggle',
                tooltip=(
                    'Whether to change the CRT overlay with the watched status of the Episode. '
                    'Either <v>True</v> or <v>False</v>. Default is <v>False</v>. '
                    'Will only work if the CRT TV Overlay Toggle is enabled.'
```

2024-07-24 21:56 UTC, CollinHeist commented on Supremicus/DawnTitleCard.py
> +        symbol: str = None
```suggestion
```
This does not seem to be used

2024-07-24 21:56 UTC, CollinHeist commented on Supremicus/DawnTitleCard.py
> +        vertical_shift = 50 + self.font_vertical_shift
```suggestion
```
Unused

2024-07-24 21:56 UTC, CollinHeist commented on Supremicus/DawnTitleCard.py
> +            if self.crt_state_overlay:
```suggestion
            if self.crt_state_overlay and not self.watched:
```

2024-07-24 21:56 UTC, CollinHeist commented on Supremicus/DawnTitleCard.py
> +            if self.crt_state_overlay:
```suggestion
            if self.crt_state_overlay and not self.watched:
```

2024-07-24 21:56 UTC, CollinHeist commented on Supremicus/HorizonTitleCard.py
> +    __GRADIENT_IMAGE = str(RemoteFile('Supremicus', 'ref/overlays/radial_gradient.png'))
```suggestion
    EPISODE_TEXT_FONT = RemoteFile('Supremicus', 'ref/fonts/ExoSoft-Medium.ttf')

    """Source path for symbol images to be overlayed behind text"""
    __SYMBOL_IMAGE_ACOLYTE = RemoteFile('Supremicus', 'ref/symbols/acolyte.png')
    __SYMBOL_IMAGE_AHSOKA = RemoteFile('Supremicus', 'ref/symbols/ahsoka.png')
    __SYMBOL_IMAGE_ANDOR = RemoteFile('Supremicus', 'ref/symbols/andor.png')
    __SYMBOL_IMAGE_BOBAFETT = RemoteFile('Supremicus', 'ref/symbols/bobafett.png')
    __SYMBOL_IMAGE_MANDALORIAN = RemoteFile('Supremicus', 'ref/symbols/mandalorian.png')
    __SYMBOL_IMAGE_OBIWAN = RemoteFile('Supremicus', 'ref/symbols/obiwan.png')
    __SYMBOL_IMAGE_WITCHER = RemoteFile('Supremicus', 'ref/symbols/witcher.png')

    """Alignment overlay image"""
    __ALIGNMENT_OVERLAY_IMAGE = RemoteFile('Supremicus', 'ref/overlays/overlay_alignment.png')

    """Source path for CRT overlays to be overlayed if enabled"""
    __OVERLAY_PLAIN = RemoteFile('Supremicus', 'ref/overlays/overlay_plain.png')
    __OVERLAY_PLAIN_BEZEL = RemoteFile('Supremicus', 'ref/overlays/overlay_plain_bezel.png')
    __OVERLAY_PLAY = RemoteFile('Supremicus', 'ref/overlays/overlay_play.png')
    __OVERLAY_PLAY_BEZEL = RemoteFile('Supremicus', 'ref/overlays/overlay_play_bezel.png')
    __OVERLAY_REWIND = RemoteFile('Supremicus', 'ref/overlays/overlay_rewind.png')
    __OVERLAY_REWIND_BEZEL = RemoteFile('Supremicus', 'ref/overlays/overlay_rewind_bezel.png')

    """Source path for the gradient image"""
    __GRADIENT_IMAGE = RemoteFile('Supremicus', 'ref/overlays/radial_gradient.png')
```

2024-07-24 21:56 UTC, CollinHeist commented on Supremicus/HorizonTitleCard.py
> +        symbol: str = None
```suggestion
        symbol: Optional[str] = None
```

2024-07-24 21:56 UTC, CollinHeist commented on Supremicus/HorizonTitleCard.py
> +                description='Color to use for the episode & title text stroke.',
```suggestion
                description='Color to use for the episode & title text stroke',
```

2024-07-24 21:56 UTC, CollinHeist commented on Supremicus/HorizonTitleCard.py
> +                description='Character to separate season and episode text.',
```suggestion
                description='Character to separate season and episode text',
```

2024-07-24 21:56 UTC, CollinHeist commented on Supremicus/HorizonTitleCard.py
> +                description='Horizontal alignment of text and symbol.',
```suggestion
                description='Horizontal alignment of the text and symbol',
```

2024-07-24 21:56 UTC, CollinHeist commented on Supremicus/HorizonTitleCard.py
> +                    '<b>Custom</b>: <v>logo</v>. Files > Logo > Upload. '
```suggestion
                description='Add a custom symbol behind the text',
                tooltip=(
                    'Either <v>acolyte</v>, <v>ahsoka</v>, <v>andor</v>, <v>bobafett<v>, '
                    '<v>mandalorian</v>, <v>obiwan</v>, or <v>witcher</v> to use a built-in '
                    'symbol, or <v>logo</v> to use the Series logo.'
```

2024-07-24 21:56 UTC, CollinHeist commented on Supremicus/HorizonTitleCard.py
> +                    'Default is <v>None</v>.'
```suggestion
                description='CRT TV Overlay Toggle',
                tooltip=(
                    'Either <v>nobezel</v> or <v>bezel</v>. Default is <v>None</v>.'
```

2024-07-24 21:56 UTC, CollinHeist commented on Supremicus/HorizonTitleCard.py
> +                    'Will only work if CRT TV Overlay is enabled.'
```suggestion
                description='CRT TV Overlay Watched-Status Toggle',
                tooltip=(
                    'Whether to change the CRT overlay with the watched status of the Episode. '
                    'Either <v>True</v> or <v>False</v>. Default is <v>False</v>. '
                    'Will only work if the CRT TV Overlay Toggle is enabled.'
```

2024-07-24 21:56 UTC, CollinHeist commented on Supremicus/HorizonTitleCard.py
> +                    ' Default is <v>False</v>.'
```suggestion
                description='Alignment Overlay Toggle',
                tooltip=(
                    'Enable an alignment overlay to help assist adjusting offsets for '
                    'misaligned custom fonts. The overlay has guiding lines every 10 pixels '.
                    'Either <v>True</v> or <v>False</v>. Default is <v>False</v>.'
```

2024-07-24 21:56 UTC, CollinHeist commented on Supremicus/HorizonTitleCard.py
> +    ARCHIVE_NAME = 'horizon'
```suggestion
    ARCHIVE_NAME = 'Horizon'
```

2024-07-24 21:56 UTC, CollinHeist commented on Supremicus/HorizonTitleCard.py
> +        vertical_shift = 40 + self.font_vertical_shift
```suggestion
```
Unused

2024-07-24 21:56 UTC, CollinHeist commented on Supremicus/HorizonTitleCard.py
> +            if self.crt_state_overlay:
```suggestion
            if self.crt_state_overlay and not self.watched:
```

2024-07-24 21:56 UTC, CollinHeist commented on Supremicus/HorizonTitleCard.py
> +            if self.crt_state_overlay:
```suggestion
            if self.crt_state_overlay and not self.watched:
```

2024-07-24 21:56 UTC, CollinHeist commented on Supremicus/HorizonTitleCard.py
> +            f'-composite',
```suggestion

        if not self.alignment_overlay:
            return []

        return [
            f'"{self.__ALIGNMENT_OVERLAY_IMAGE.resolve()}"',
            f'-composite',
```

2024-07-24 23:02 UTC, Supremicus commented
@CollinHeist Cards updated from code review suggestions

2024-07-25 04:37 UTC, CollinHeist commented
Looks great! Thanks again.

2024-07-25 04:37 UTC, merged